# Generated by Django 2.2.2 on 2019-06-20 07:39

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Type de réunion')),
                ('folder_name', models.CharField(help_text='Exemple : CR_AG', max_length=10, unique=True, verbose_name='Nom dossier stockage')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple : 2018/2019', max_length=30, verbose_name='Date du mandat')),
                ('upload_active', models.BooleanField(default=True)),
                ('folder_name', models.CharField(help_text='Exemple : 2018-2019', max_length=10, unique=True, verbose_name='Nom dossier stockage')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la réunion')),
                ('file', models.FileField(upload_to=app.models.report_file_name, verbose_name='Fichier CR')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('download_number', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Type', verbose_name='Type de réunion')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Year', verbose_name='Mandat')),
            ],
        ),
    ]
