# Generated by Django 2.2.2 on 2019-06-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Type de réunion')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple : 2018/2019', max_length=30, verbose_name='Date du mandat')),
                ('upload_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la réunion')),
                ('media', models.FileField(upload_to='', verbose_name='Fichier CR')),
                ('is_public', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Type', verbose_name='Type de réunion')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Year', verbose_name='Mandat')),
            ],
        ),
    ]
