# Generated by Django 2.2.2 on 2019-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
