# Generated by Django 2.2.2 on 2019-06-19 09:12

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_download_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='media',
            field=models.FileField(verbose_name='Fichier CR'),
        ),
    ]
