# Generated by Django 2.2.2 on 2019-06-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190619_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='media',
            new_name='file',
        ),
    ]
