# Generated by Django 2.2.2 on 2019-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190619_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Fichier CR'),
        ),
    ]
